operate-first/community

OWNERS

chore: Add quaid to OWNERS

---

.prow.yaml

update the resource limit for the prowjobs
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
Fixes: https://github.com/operate-first/community/pull/43#issuecomment-872570243
Related-to: https://github.com/thoth-station/thoth-application/issues/1332

update the resource limit for the prowjobs

---

core_project_message.md

This is created using the messages on operate-first.cloud as a seed, reference, and grist for evolving into a message in layers that builds on itself.
This file is in response to issue #4 .

Created from existing messages for hacking-on

---

governance.md

- Content was ratified in operate-first/community#107
- These changes make it clear to the reader this is the actual formal docuemnt

Completion of draft stage, no longer WIP

---

.github/workflows/book.yml
yamllint-config.yaml

This should have been part of: https://github.com/operate-first/community/pull/115 
But it got omitted in my git add since it's a `.*` folder :)

Add git action for jbook build.

---

.github/workflows/book.yml

Fix path to requirements file in gitaction.

---

.github/workflows/book.yml

Fix path to pub dir in gitaction.

---

sig-community/charter.md
sigs.yaml

- Includes as many purviews as I could think of
- Some of these will be turned over to other SIGs
- This PR is not intended to be final as initially made;
rather, it is for discussion and changes to this document
to come from those discussions, all within the space of
the pull request.

Strawpond charter for throwing pebbles at

---

sig-operations/subprojects/ops-docs/OWNERS

Added myself to the OWNERS list of the ops-docs subproject

add carlosgimeno to sig-operations/ops-docs subproject

---

sig-list.md
sig-operations/README.md
sigs.yaml

This change will regenerate the sigops readme to add the meeting
times for the clusterops subproject.

Regenerate sigops files.

---

OWNERS

We need more approvers, but that can be something the SIG figures out.

Reflecting changes since forming SIG

---

sigs.yaml

cc @sallyom @stefwrite @quaid 
am I missing somebody else?

add Contrib_X Docs group

---

sigs.yaml

cc @hpdempsey @quaid @stefwrite @bryanmontalvan

add Website Updates WG

---

sig-operations/README.md

As discussed in our meeting today.

Add Meeting notes link to sig operations 

---

sig-community/wg-contrib_x-docs/meeting-notes/20220315-meeting-ntoes.md

WG kickoff planning session, with actions

---

sig-community/wg-website-updates/meeting-notes/20220322-meeting-notes.md

- This is fine right now, and I'll merge the PR myself, so we're
following gitops procedures in general.
- But what is a useful commit message for a meeting notes?
- Especially the first line
- It could have meaningful highlights?

First meeting minutes for new WG, more process needed

---

open-source-services.md

In order to understand the open source services document, I felt it was fundamental to have a definition of what a service is in order to evaluate the criteria. I am attempting here to provide a first draft definition of a service to the FAQ to help developers with their evaluations.

Add definition of service to FAQ for open source service

---

sig-community/meeting-notes/20220407-meeting-notes.md

SIG Community bi-weekly for 2022-04-07

---

sig-community/wg-website-updates/meeting-notes/20220412-meeting-notes.md

Minutes from 2022-04-12 Website Updates WG meeting

---

sig-telemetry/README.md

Fix typos and bad links

---

users/data-scientist.md

Partially address #180 by adding a doc for a Data Science Persona. I'm not sure if I correctly filled out all the sections, might need some extra work by a communications persona in a follow up PR. :smile:

add data science persona

---

four-principles.md

Updates as worked out with Karsten

Update wording to be more open and inclusive.

---

glossary.md

Lots of cruft and old discussion material removed.
Reformatted for easier reading and maintaining.
Updated content e.g. for NERC, MOC Alliance, etc.

Clean-up and addition of how-to-naming details

---

_toc.yml

- Could do a bit of reorganizing still
- Does not address fixes needed in the SIGs section

Pages missing from TOC

---

_toc.yml
community-cloud-faq.md

Making a stub file and URL

---

community-cloud-faq.md

- Primarily from Slack discussions
- Includes links to various how-to locations

Updates with answers to questions received
